export const projects = [
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_1_1",
    desc2: "proj_desc_1_2",
    desc3: "proj_desc_1_3",
    gallery: ["images/project1/project1-hero-1.png", "images/project1/project1-hero-2.png"],
    allGallery: [
      "images/project1/1.png",
      "images/project1/2.png",
      "images/project1/3.png",
      "images/project1/4.png",
      "images/project1/5.png",
      "images/project1/6.jpg",
      "images/project1/8.jpg",
      "images/project1/9.jpg",
      "images/project1/10.jpg",
      "images/project1/11.jpg",
      "images/project1/12.jpg",
      "images/project1/13.jpg",
      "images/project1/14.jpg",
      "images/project1/15.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_1",
    popup_details_text_above_photo: "popup_details_text_above_photo_1",
    popup_details_text_under_photo_normal: "popup_details_text_under_photo_normal_1",
    popup_details_text_bottom: "popup_details_text_bottom_1",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_2_1",
    desc2: "proj_desc_2_2",
    desc3: "proj_desc_2_3",
    gallery: ["images/project2/project3-hero-1.jpg", "images/project2/project3-hero-2.jpg"],
    allGallery: [
      "images/project2/1.jpg",
      "images/project2/2.jpg",
      "images/project2/3.jpg",
      "images/project2/4.jpg",
      "images/project2/5.jpg",

      "images/project2/6.jpg",
      "images/project2/8.jpg",
      "images/project2/9.jpg",
      "images/project2/10.jpg",
      "images/project2/11.jpg",
      "images/project2/12.jpg",
      "images/project2/13.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_2",
    popup_details_text_above_photo: "popup_details_text_above_photo_2",
    popup_details_text_under_photo_normal: "popup_details_text_under_photo_normal_2",
    popup_details_text_bottom: "popup_details_text_bottom_2",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_3_1",
    desc2: "proj_desc_3_2",
    desc3: "proj_desc_3_3",
    gallery: ["images/project3/hero-1.jpg", "images/project3/2.png"],
    allGallery: [
      "images/project3/7.jpg",
      "images/project3/1.jpg",
      "images/project3/2.jpg",
      "images/project3/3.jpg",
      "images/project3/10.jpg",
      "images/project3/4.jpg",
      "images/project3/5.jpg",
      "images/project3/6.jpg",
      "images/project3/8.jpg",
      "images/project3/9.jpg",
      "images/project3/11.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_3",
    popup_details_text_above_photo: "popup_details_text_above_photo_3",
    popup_details_text_under_photo_normal: "popup_details_text_under_photo_normal_3",
    popup_details_text_bottom: "popup_details_text_bottom_2",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_4_1",
    desc2: "proj_desc_4_2",
    desc3: "proj_desc_4_3",
    gallery: ["images/project4/hero-1.jpg", "images/project4/1.jpg"],
    allGallery: [
      "images/project4/1.jpg",
      "images/project4/2.jpg",
      "images/project4/3.jpg",
      "images/project4/4.jpg",
      "images/project4/5.jpg",
      "images/project4/6.jpg",
      "images/project4/7.jpg",
      "images/project4/8.jpg",
      "images/project4/9.jpg",
      "images/project4/10.jpg",
      "images/project4/11.jpg",
      "images/project4/12.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_4",
    popup_details_text_above_photo: "popup_details_text_above_photo_4",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_5_1",
    desc2: "proj_desc_5_2",
    desc3: "proj_desc_5_3",
    gallery: ["images/project5/hero-1.jpg", "images/project5/1.jpg"],
    allGallery: [
      "images/project5/1.jpg",
      "images/project5/2.jpg",
      "images/project5/3.jpg",
      "images/project5/4.jpg",
      "images/project5/5.jpg",
      "images/project5/6.jpg",
      "images/project5/7.jpg",
      "images/project5/8.jpg",
      "images/project5/9.jpg",
      "images/project5/10.jpg",
      "images/project5/11.jpg",
      "images/project5/12.jpg",
      "images/project5/13.jpg",
      "images/project5/14.jpg",
      "images/project5/15.jpg",
      "images/project5/16.jpg",
      "images/project5/17.jpg",
      "images/project5/18.jpg",
      "images/project5/19.jpg",
      "images/project5/20.jpg",
      "images/project5/21.jpg",
      "images/project5/22.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_5",
    popup_details_text_above_photo: "popup_details_text_above_photo_5",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_6_1",
    desc2: "proj_desc_6_2",
    desc3: "proj_desc_6_3",
    gallery: ["images/project6/1.jpg", "images/project6/2.jpg"],
    allGallery: [
      "images/project6/1.jpg",
      "images/project6/2.jpg",
      "images/project6/3.jpg",
      "images/project6/4.jpg",
      "images/project6/5.jpg",
      "images/project6/6.jpg",
      "images/project6/7.jpg",
      "images/project6/8.jpg",
      "images/project6/9.jpg",
      "images/project6/10.jpg",
      "images/project6/11.jpg",
      "images/project6/12.jpg",
      "images/project6/13.jpg",
      "images/project6/14.jpg",
      "images/project6/15.jpg",
      "images/project6/16.jpg",
      "images/project6/17.jpg",
      "images/project6/18.jpg",
      "images/project6/19.jpg",
      "images/project6/20.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_6",
    popup_details_text_above_photo: "popup_details_text_above_photo_6",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_7_1",
    desc2: "proj_desc_7_2",
    desc3: "proj_desc_7_3",
    gallery: ["images/project7/1.jpg", "images/project7/2.jpg"],
    allGallery: [
      "images/project7/1.jpg",
      "images/project7/2.jpg",
      "images/project7/3.jpg",
      "images/project7/4.jpg",
      "images/project7/5.jpg",
      "images/project7/6.jpg",
      "images/project7/7.jpg",
      "images/project7/8.jpg",
      "images/project7/9.jpg",
      "images/project7/10.jpg",
      "images/project7/11.jpg",
      "images/project7/12.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_7",
    popup_details_text_above_photo: "popup_details_text_above_photo_7",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_8_1",
    desc2: "proj_desc_8_2",
    desc3: "proj_desc_8_3",
    gallery: ["images/project8/1.jpg", "images/project8/2.jpg"],
    allGallery: [
      "images/project8/1.jpg",
      "images/project8/2.jpg",
      "images/project8/3.jpg",
      "images/project8/4.jpg",
      "images/project8/5.jpg",
      "images/project8/6.jpg",
      "images/project8/7.jpg",
      "images/project8/8.jpg",
      "images/project8/9.jpg",
      "images/project8/10.jpg",
      "images/project8/11.jpg",
      "images/project8/12.jpg",
      "images/project8/13.jpg",
      "images/project8/14.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_8",
    popup_details_text_above_photo: "popup_details_text_above_photo_8",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
  {
    done: true,
    label: "proj_label_done",
    title: "finished_proj_desc_title",
    desc1: "proj_desc_9_1",
    desc2: "proj_desc_9_2",
    desc3: "proj_desc_9_3",
    gallery: ["images/project9/1.jpg", "images/project9/2.jpg"],
    allGallery: [
      "images/project9/1.jpg",
      "images/project9/2.jpg",
      "images/project9/3.jpg",
      "images/project9/4.jpg",
      "images/project9/5.jpg",
      "images/project9/6.jpg",
      "images/project9/7.jpg",
      "images/project9/8.jpg",
      "images/project9/9.jpg",
      "images/project9/10.jpg",
      "images/project9/11.jpg",
      "images/project9/12.jpg",
    ],
    popup_details_subtitle: "popup_details_subtitle_9",
    popup_details_text_above_photo: "popup_details_text_above_photo_9",
    popup_details_text_under_photo_normal: "",
    popup_details_text_bottom: "",
  },
];
